export const municipios = [
  "Alaquàs",
  "Albal",
  "Albalat de la Ribera",
  "Alborache",
  "Alcàsser",
  "(l') Alcúdia",
  "Aldaia",
  "Alfafar",
  "Alfarb",
  "Algemesí",
  "Alginet",
  "Almussafes",
  "Alzira",
  "Benetússer",
  "Benicull de Xúquer",
  "Benifaió",
  "Beniparrell",
  "Bétera",
  "Bugarra",
  "Buñol",
  "Calles",
  "Camporrobles",
  "Carlet",
  "Catadau",
  "Catarroja",
  "Caudete de las Fuentes",
  "Corbera",
  "Cullera",
  "Chera",
  "Cheste",
  "Chiva",
  "Dos Aguas",
  "Favara",
  "Fortaleny",
  "Fuenterrobles",
  "Gestalgar",
  "Godelleta",
  "Guadassuar",
  "Llíria",
  "Loriguilla (sólo núcleo urbano junto a la A-3)",
  "Llaurí",
  "Llocnou de la Corona",
  "Llombai",
  "Macastre",
  "Manises",
  "Manuel",
  "Massanassa",
  "Mislata",
  "Montserrat",
  "Montroi",
  "Paiporta",
  "Paterna",
  "Pedralba",
  "Picanya",
  "Picassent",
  "Pobla Llarga",
  "Polinyà de Xúquer",
  "Quart de Poblet",
  "Rafelguaraf",
  "Real",
  "Requena",
  "Riba-roja de Túria",
  "Riola",
  "Sedaví",
  "Senyera",
  "Siete Aguas",
  "Silla",
  "Sinarcas",
  "Sollana",
  "Sot de Chera",
  "Sueca",
  "Tavernes de la Valldigna",
  "Torrent",
  "Turís",
  "Utiel",
  "València (pedanías del sur: Faitanar, La Torre, Forn d'Alcedo, Castellar-Oliveral, Pinedo, el Saler, el Perelló y el Palmar)",
  "Vilamarxant",
  "Xirivella",
  "Yátova",
] as const;

export type Municipio = (typeof municipios)[number];
